### ISSUE TITLE
P181 5行目の式について

### ISSUE THREAD

**Issue by devemin** [makaishi2/math_dl_book_info#2]
こんにちは。楽しく書籍を読ませていただいております。
内容について、どこから問い合わせれば良いかわからなかったので、
こちらに書かせていただきます。

P181の5行目の式において、
∂(yd(w0, w1)) / ∂w1   =   ∂(yp(w0, w1)) / ∂w1    =   ∂(w0x0 + w1x1) / ∂w1   =   x1
は、
∂(yd(w0, w1)) / ∂w1   =   ∂(yp(w0, w1) **- yt** ) / ∂w1    =   ∂(w0x0 + w1x1 **- yt**) / ∂w1   =   x1

ですか？
私は数学に弱くて、全然見当違いだったならば申し訳ありませんが・・・

お手すきの際にご返信頂ければ幸いです。
宜しくお願い致します。

**Comment by devemin** [comment]
ふたたびすみません。

p150 の図5-11 ですが、出力の数値
0.0351   0.2595   0.7354
は、
0.0351   0.2595   **0.7054**
のように思えます。
宜しくお願い致します。

**Comment by devemin** [comment]
たびたび申し訳ありません・・・

p269 9行目　768(=28x28)　→　**784** (=28x28)
　　  13行目　CNNついては　→　CNN**に**ついては

p289 2-3行目　60000　→　20、　512　→　5

ではないかと思いますが、ご確認頂ければ幸いです。
宜しくお願い致します。


ようやく1度、最後まで読破し、非常に有意義な時間を過ごせました。
今後もこの本を参考にディープラーニングを学んでいこうと思います。
ありがとうございました。

**Comment by makaishi2** [comment]
でべ様、細かいところまで読み込んでいただけたようで、ありがとうございます。このような読者の方がいらっしゃると著者冥利に尽きます。

以下のとおり、ご質問に回答いたします。誤植の箇所については、早々に対応を取らせていただく予定です。
今後ともよろしくお願いいたします。

=======================

p150 の図5-11: 
ご指摘のとおりです。

P181の5行目の式: 
学習フェーズではytは定数の扱いになります。
なので、微分(偏微分も微分の一種です)の結果はゼロになり、途中経過はでべ様の式の通りですが、最終的には本の数式となります。

p.269:
2箇所ともご指摘の通りです。

p.289:
サンプルコードの引数は20と5なのですが、その後のディープラーニングの学習コードの引数は6000と512になっています。今の説明文ではその違いがわかりにくいので、説明の仕方を考えます。

**Comment by devemin** [comment]
ご確認ありがとうございます。
すっきりしました。

逆に、この本を作るのにどれだけの労力がかかったのか、逆算的にどのようにこの本を作ったのかの記載など読みまして感動しました。

元々教育者の端くれだったので、そんな事を考えてしまいました。
今後も応援しております。

宜しくお願い致します。
坂口
