### ISSUE TITLE
P75 コラム積分記号の意味

### ISSUE THREAD

**Issue by hiroyoshi-suyama** [makaishi2/math_dl_book_info#3]
Kindle版で読ませていただいております。

p75 コラム「積分記号の意味」の部分にて、
「今までの説明でわかった通り、定積分とは結局タテf(x)、ヨコdxの細かい短冊状の長方形の区間をaから区間bまで敷き詰めて、全部足し合わせるイメージになります」
とありますが、p72の図2-15やその説明を読む限り、積分は「細かい短冊上の長方形」＋「dx増加分の三角形」の面積を表しているように思います。

長方形だけを足し合わせたもの。のように読み取れるため困惑しております。
なぜここでは台形ではなく、長方形なのでしょうか？

お手すきの際にご返信頂ければ幸いです。
宜しくお願い致します。

**Comment by makaishi2** [comment]
コメントいただきありがとうございます。同じ質問を過去にも一度受けていたので、質問とその回答はFAQに追加させていただきました。こちらのISSUEについてはcloseとさせていただきます。
今後もよろしくお願いいたします。

**Comment by hiroyoshi-suyama** [comment]
確認しました。
理解しました。ありがとうございます。
