### ISSUE TITLE
p26 2行目

### ISSUE THREAD

**Issue by mctk-imamura** [makaishi2/math_dl_book_info#4]
数か月前に本書でディープラーニングを学び始め、最近はKeras(TensorFlow)を用いてモデル作成をしています。本書も時々見返します。

p26　2行目ですが、「個々の点から予測値を表す直線に垂直に下した直線の長さ」とありますが、垂直ではないと思います。(x軸には垂直ですがそういった意味にとらえることができる文章ではないと思います。)

**Comment by makaishi2** [comment]
コメントいただきありがとうございました。
正しいご指摘だったので、正誤訂正に追記し次回4刷の時に修正予定です。
今後ともよろしくお願いいたします。
