### ISSUE TITLE
p259 下から7行目

### ISSUE THREAD

**Issue by kinmojr** [makaishi2/math_dl_book_info#5]
1版2刷のp259の下から7行目ですが、
「yt, yp, yd：数値 → ベクトル」ではなく、
「yt, yp, yd：ベクトル → 行列」ではないでしょうか？
(そうだとすると、1行したのWと同じになりますが)

**Comment by makaishi2** [comment]
コメントいただきありがとうございます。
ご指摘の内容はその通りだったので、正誤訂正に追記しました。

https://github.com/makaishi2/math_dl_book_info/blob/master/errors.md

あわせて、近々出版予定の4刷では修正予定です。
今後ともよろしくお願いいたします。
