### ISSUE TITLE
図9-7の重み行列Wのインデックスiとjについて

### ISSUE THREAD

**Issue by kinmojr** [makaishi2/math_dl_book_info#6]
issueではなく質問なのですが、図9-7の重み行列Wのインデックスiとjは、iが列のインデックスでjが行のインデックスという理解で合っていますか？

**Comment by makaishi2** [comment]
ご質問いただき、ありがとうございます。
ここは、行と列の区別が曖昧なため、とてもわかりにくくなってしまっている箇所で、結論としてご質問いただいている理解であっています。
ご参考までに、他の読者の方からはp.258のWの次元が(D,N)でなく(N,D)なのではというご質問もいただいていて、その回答はFAQに記載しています。

https://github.com/makaishi2/math_dl_book_info/blob/master/faqs.md

**Comment by kinmojr** [comment]
なるほど、理解できました。ありがとうございました。
