### ISSUE TITLE
p.184 j=0とp.269 デープラーニング

### ISSUE THREAD

**Issue by kinmojr** [makaishi2/math_dl_book_info#7]
p.184の「(7.8.3)はj=0, 1」ですが、jではなくiではないでしょうか。

p.269 「デープラーニング」はディープラーニングだと思います。

**Comment by makaishi2** [comment]
ご指摘ありがとうございます。
p.184の方に関しては、正誤訂正に追記しましたので、ご確認下さい。
p.269の方は、このままで文意は通じるので正誤訂正には入れていませんが、近々出る予定の5刷では修正予定です。
今後も、おかしな表記がありましたら、ご連絡いただけると幸いです。
よろしくお願いいたします。
